sfu-db/connector-x

- Cargo.lock
- Justfile
- connector-agent-python/Cargo.toml
- connector-agent-python/connector_agent_python/tests/test_read_sql.py
- connector-agent-python/src/pandas/pandas_columns/string.rs
- connector-agent-python/src/pandas/pystring.rs
- connector-agent/src/sources/postgres/mod.rs
- connector-agent/src/sources/postgres/sql.rs
- scripts/postgres.sql
#36 
* fix bug on counting rows when sql has limit
* string support for non ascii
> string support for non ascii

- connector-agent-python/src/pandas/destination.rs
- connector-agent-python/src/pandas/mod.rs
- connector-agent-python/src/pandas/pandas_columns/boolean.rs
- connector-agent-python/src/pandas/pandas_columns/datetime.rs
- connector-agent-python/src/pandas/pandas_columns/float64.rs
- connector-agent-python/src/pandas/pandas_columns/int64.rs
- connector-agent-python/src/pandas/pandas_columns/mod.rs
- connector-agent-python/src/pandas/pandas_columns/string.rs
- connector-agent-python/src/pandas/transport.rs
- connector-agent-python/src/read_sql.rs
- connector-agent/src/destinations/arrow/arrow_assoc.rs
- connector-agent/src/destinations/arrow/funcs.rs
- connector-agent/src/destinations/arrow/mod.rs
- connector-agent/src/destinations/memory/mod.rs
- connector-agent/src/dispatcher.rs
- connector-agent/src/errors.rs
- connector-agent/src/partition.rs
- connector-agent/src/sources/csv.rs
- connector-agent/src/sources/postgres/mod.rs
- connector-agent/src/sources/postgres/sql.rs
- connector-agent/tests/test_postgres.rs
> Remove unwraps / expects

- connectorx-python/connectorx/tests/test_read_sql.py
- connectorx/src/errors.rs
- connectorx/src/partition.rs
- connectorx/src/sources/postgres/sql.rs
- connectorx/tests/test_postgres.rs
#66 
1. fix count query result for aggregation
2. throw error for none SPJ queries
> Handle aggregation query

- Cargo.lock
- connectorx-python/src/pandas/transport.rs
- connectorx/Cargo.toml
- connectorx/src/sources/postgres/mod.rs
- connectorx/src/sources/postgres/typesystem.rs
- connectorx/src/transports/postgres_arrow.rs
- connectorx/src/transports/postgres_memory.rs
- connectorx/tests/test_postgres.rs
- scripts/postgres.sql
Worked on int16, char, uuid, time, interval, but incomplete.
> Add Postgres types (incomplete)

- benchmarks/tpch-cx.py
- connectorx-python/connectorx/tests/test_read_sql.py
- connectorx/src/partition.rs
- connectorx/src/sources/postgres/sql.rs
- scripts/postgres.sql
* partition use nested query
* add tests for aggregation and udf
> Partition via nested query: support aggregation

- connectorx-python/connectorx/tests/test_read_sql.py
- connectorx-python/pyproject.toml
- connectorx/src/partition.rs
> version 0.1.1

- connectorx-python/connectorx/tests/test_read_sql.py
- connectorx-python/connectorx/tests/test_sqlite.py
- connectorx/src/sources/postgres/mod.rs
- connectorx/src/sources/sqlite/mod.rs
#86 
* use copy csv headers in postgres
* use rows.column_name() in sqlite
* add tests
> Get headers when zero tuple returned from postgres and sqlite

- .deepsource.toml
- .github/workflows/ci.yml
- Cargo.lock
- Justfile
- benchmarks/tpch-pandas.py
- connectorx-python/Cargo.toml
- connectorx-python/connectorx/tests/test_mysql.py
- connectorx-python/connectorx/tests/test_read_sql.py
- connectorx-python/poetry.lock
- connectorx-python/pyproject.toml
- connectorx-python/src/pandas/mod.rs
- connectorx-python/src/pandas/transports/mod.rs
- connectorx-python/src/pandas/transports/mysql.rs
- connectorx-python/src/pandas/transports/postgres.rs
- connectorx/Cargo.toml
- connectorx/src/errors.rs
- connectorx/src/lib.rs
- connectorx/src/source_router.rs
- connectorx/src/sources/mod.rs
- connectorx/src/sources/mysql/mod.rs
- connectorx/src/sources/mysql/typesystem.rs
- connectorx/src/sources/postgres/mod.rs
- connectorx/src/sql.rs
- connectorx/tests/test_mysql.rs
- scripts/mem_monitor.sh
- scripts/mysql.sql
#88 
since I don't have the permission directly modify on the original forked repo
> Redirect Mysql PR

- connectorx-python/connectorx/__init__.py
- connectorx-python/connectorx/tests/test_read_sql.py
- connectorx-python/src/lib.rs
- connectorx-python/src/pandas/destination.rs
- connectorx-python/src/pandas/mod.rs
- connectorx-python/src/pandas/pandas_columns/boolean.rs
- connectorx-python/src/pandas/pandas_columns/bytes.rs
- connectorx-python/src/pandas/pandas_columns/datetime.rs
- connectorx-python/src/pandas/pandas_columns/int64.rs
- connectorx-python/src/pandas/pandas_columns/mod.rs
- connectorx-python/src/pandas/pandas_columns/string.rs
- connectorx-python/src/pandas/pystring.rs
- connectorx-python/src/pandas/types.rs
- connectorx/src/sources/postgres/mod.rs
- connectorx/src/sources/sqlite/typesystem.rs
- scripts/postgres.sql
#94 
* Destination workflow changes as follow:
1. allocate numpy arrays in destination
2. write data from source to numpy arrays
3. convert numpy arrays into pandas through blockmanager
* Fix bug that treating "" as None for string and bytes and add corresponding tests
Tested on pandas 1.2.3 and 1.3.0
> Support pandas 1.3

- Cargo.lock
- connectorx/Cargo.toml
- connectorx/src/destinations/arrow2/arrow_assoc.rs
- connectorx/src/destinations/arrow2/errors.rs
- connectorx/src/destinations/arrow2/funcs.rs
- connectorx/src/destinations/arrow2/mod.rs
- connectorx/src/destinations/arrow2/typesystem.rs
- connectorx/src/destinations/mod.rs
Adds support for arrow2. Closes #113
> Added support for arrow2

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- Cargo.lock
- connectorx-python/src/arrow.rs
- connectorx-python/src/pandas/destination.rs
- connectorx/Cargo.toml
- connectorx/src/destinations/arrow/mod.rs
- connectorx/src/destinations/arrow2/mod.rs
- connectorx/src/destinations/mod.rs
- connectorx/src/dispatcher.rs
- connectorx/src/sources/mod.rs
- connectorx/src/sources/mysql/mod.rs
- connectorx/src/sources/oracle/mod.rs
- connectorx/src/sources/sqlite/mod.rs
- connectorx/src/transports/postgres_arrow.rs
- connectorx/src/transports/postgres_arrow2.rs
Update PR: https://github.com/sfu-db/connector-x/pull/170
> Fix postgres to arrow type: bytea

- Cargo.lock
- connectorx/Cargo.toml
- connectorx/src/destinations/mod.rs
- connectorx/src/sources/mod.rs
- connectorx/src/transports/postgres_arrow.rs
- connectorx/src/transports/postgres_arrow2.rs
Fixes #148. Depends on https://github.com/pola-rs/polars/commit/dd70f3167f53e4ba59a0fe9c2f8aca18cdbb6b0d
> Fix postgres bytea

- Cargo.lock
- connectorx/Cargo.toml
- connectorx/src/sources/mssql/mod.rs
Reverts sfu-db/connector-x#183
> Revert "Mssql trusted connection support"

- connectorx/src/sources/mssql/mod.rs
> support windows trusted connection

- .github/workflows/release.yml
- CONTRIBUTING.md
- Cargo.toml
- Justfile
- connectorx-python/.cargo/config
- connectorx-python/Cargo.lock
- connectorx-python/Cargo.toml
- connectorx-python/connectorx/__init__.py
- connectorx-python/connectorx/tests/test_oracle.py
- connectorx-python/poetry.lock
- connectorx-python/pyproject.toml
- connectorx-python/src/lib.rs
- connectorx/Cargo.toml
- scripts/python-helper.py
https://github.com/sfu-db/connector-x/actions/runs/1973865849
> various improve on ci and add apple arm

- connectorx-python/connectorx/tests/test_oracle.py
- connectorx/src/sources/oracle/typesystem.rs
- scripts/oracle.sql
Fixed the oracle invalid digit issue.
> fix oracle round function issue

- Cargo.lock
- connectorx-python/Cargo.lock
- connectorx-python/Cargo.toml
- connectorx-python/pyproject.toml
- connectorx/Cargo.toml
Build crash with gcp-bigquery-client=0.10.0, 0.10.2
> Upgrade gcp-bigquery-client to 0.13.0

- Cargo.lock
- connectorx-cpp/Cargo.toml
- connectorx-python/Cargo.lock
- connectorx-python/Cargo.toml
- connectorx/Cargo.toml
- connectorx/src/source_router.rs
From #397 , + align arrow version in python and cpp modules @gruuya
> Datafusion 14 arrow 26 upgrade

- connectorx/src/transports/mod.rs
before: `cargo build --features "dst_arrow2 src_bigquery"` failed, now it works
> fix build only with src_bigquery and dst_arrow2

- connectorx-python/pyproject.toml
https://maturin.rs/changelog.html
Closes #522
> Upgrade maturin to 1.0

- Cargo.lock
Reverts sfu-db/connector-x#591
> Revert "build(rust): bump openssl from 0.10.63 to 0.10.64"

- connectorx-python/connectorx/__init__.py
Signed-off-by: ZhengYu, Xu <zen-xu@outlook.com>
> refactor: simplify ternary operator

- .gitignore
- connectorx-python/connectorx/tests/test_arrow.py
- connectorx/src/destinations/arrow/arrow_assoc.rs
- connectorx/src/destinations/arrow/typesystem.rs
- connectorx/src/destinations/arrow2/arrow_assoc.rs
- connectorx/src/destinations/arrow2/typesystem.rs
- connectorx/src/sources/oracle/typesystem.rs
- connectorx/src/transports/mssql_arrow.rs
- connectorx/src/transports/mssql_arrow2.rs
- connectorx/src/transports/mysql_arrow.rs
- connectorx/src/transports/mysql_arrow2.rs
- connectorx/src/transports/oracle_arrow.rs
- connectorx/src/transports/oracle_arrow2.rs
- connectorx/src/transports/postgres_arrow.rs
- connectorx/src/transports/postgres_arrow2.rs
Done: postgres->arrow2
Todo:
* sources: postgres, oracle, sqlserver
* dest: arrow, arrow2
* add more tests
> [WIP] Adding microsecond timestamp type, fix #644 #634

- connectorx-python/connectorx/__init__.py
The problem is analyzed here: https://github.com/sfu-db/connector-x/issues/653
> Change ValueError exception to ModuleNotFoundError

- connectorx/src/sources/mssql/mod.rs
Resolves https://github.com/sfu-db/connector-x/issues/783
> URL decode database name for MSSQL

- connectorx/src/sources/mssql/mod.rs
Resolves https://github.com/sfu-db/connector-x/issues/707
> Add `EncryptionLevel::Off` for MSSQL
