sfu-db/connector-x

connectorx-python/connectorx/tests/test_read_sql.py
connectorx/src/partition.rs

original selection should not move out from the nested query

fix bug on partition

---

connectorx/src/constants.rs
connectorx/src/destinations/arrow/arrow_assoc.rs
connectorx/src/lib.rs
connectorx/tests/test_arrow.rs

This PR proposes using `LargeString` in favor of `String` type. The `String` datatype offsets the bytes in the `&str` buffer with an `i32` meaning that the columns can only hold 2^32 == ~2GB of string data. This limit is very easily met.
The `LargeString` uses an `i64` as offset type. A limit I don't see reached any time soon. :)
This also adds `Date32` and `Date64` for the naive dates/datetimes.
What would be needed next to make this work? I assume some python integration. And from the Rust side?

arrow use largestring and date32/date64

---

connectorx/src/destinations/arrow/arrow_assoc.rs
connectorx/src/destinations/arrow/mod.rs
connectorx/src/destinations/arrow/types.rs
connectorx/src/transports/dummy_arrow.rs
connectorx/src/transports/postgres_arrow.rs
connectorx/tests/test_arrow.rs

This PR adds an arrow types system and uses that type system in `PostgresArrowTransport`.
I just pleased the type system here, so please take a good look. :)
Some questions:
* what does the this [bool]( https://github.com/sfu-db/connector-x/blob/3c56c539d29bc252d205a20700edd63efec301ab/connectorx-python/src/pandas/types.rs#L8) do?
A premature optimization, but if I understand correctly we can also implement `ArrowAssoc` for `&str` and `Option<&str>`, add that to the type system and thereby reduce an allocation of `String`?

Init arrow type system and use that in postgres transport

---

Cargo.lock
Justfile
connectorx-python/Cargo.toml
connectorx-python/connectorx/tests/test_postgres.py
connectorx-python/poetry.lock
connectorx-python/pyproject.toml
connectorx-python/src/arrow.rs
connectorx-python/src/pandas/mod.rs
connectorx-python/src/pandas/transports/postgres.rs
connectorx-python/src/source_router.rs
connectorx/Cargo.toml
connectorx/src/sources/postgres/connection.rs
connectorx/src/sources/postgres/errors.rs
connectorx/src/sources/postgres/mod.rs
connectorx/src/transports/postgres_arrow.rs
connectorx/src/transports/postgres_memory.rs
connectorx/tests/test_arrow.rs
connectorx/tests/test_polars.rs
connectorx/tests/test_postgres.rs

As discussed in #103, currently there's no way to connect to a postgres database that mandates a TLS/SSL connection.
What this PR does is make it so `sslmode=required` is functional, and if a root cert and no client certs are passed it falls back to the behavior of `sslmode=verify-ca`. 
Example conn string:
```python
conn = f"postgresql://{user}:{pw}@my.database.host:5439/db?sslmode=require&sslrootcert=/tmp/myroot.crt"
df = cx.read_sql(conn, "select 1;", return_type='pandas', protocol='cursor')
```
There is a lot of upstream discussion on the topic and I've tried to link to it in doc strings where appropriate. Tested it on Amazon Redshift, but looking for pointers on how to add functional tests for this. All of the code probably isn't idiomatic rust either, so looking for some feedback …

Add SSL/TLS support for Postgres connections

---

Cargo.lock
Justfile
connectorx-python/Cargo.toml
connectorx-python/connectorx/tests/test_postgres.py
connectorx-python/src/lib.rs
connectorx-python/src/pandas/destination.rs
connectorx-python/src/pandas/pandas_columns/array.rs
connectorx-python/src/pandas/pandas_columns/bytes.rs
connectorx-python/src/pandas/pandas_columns/floatarray.rs
connectorx-python/src/pandas/pandas_columns/mod.rs
connectorx-python/src/pandas/pandas_columns/string.rs
connectorx-python/src/pandas/transports/postgres.rs
connectorx-python/src/pandas/typesystem.rs
connectorx-python/src/source_router.rs
connectorx/src/macros.rs
connectorx/src/sources/postgres/mod.rs
connectorx/src/sources/postgres/typesystem.rs
scripts/postgres.sql

#108 
Support float and int array for postgres -> pandas

Support Array Type

---

connectorx/src/sources/postgres/mod.rs

This patch solves the issue outlined in #149 on my particular database, could probably be refactored to reduce repetition but couldn't figure out how in a way I liked, any pointers? :slightly_smiling_face:

Fix for #149

---

connectorx-python/connectorx/__init__.py

A small backwards-compatible patch (no behaviour changes to any existing calls), that allows redshift-prefixed connection strings to select the correct protocol ("cursor") automatically, and proceed as if postgres. All other connections default to "binary", as before.

Automatically select 'cursor' protocol for redshift-prefixed connection strings

---

connectorx-python/connectorx/__init__.py

much the same as the previous redshift patch, but this one is for ease of use with clickhouse. sits in the same block of code quite neatly, and doesn't disturb any other defaults. hopefully of similar utility ;)
`read_sql("clickhouse://...details...", query=...)` => `read_sql("mysql://...details...", query=..., protocol='text')`

Automatically select 'text' protocol for clickhouse-prefixed connection strings

---

connectorx/src/constants.rs
connectorx/src/sources/oracle/mod.rs

https://github.com/sfu-db/connector-x/issues/127
Varying the array size could affect the performance when no partition is applied , switch to using stmt from 100 (default) to 1K(905s -> 834s)

Oracle stmt array size 1k

---

README.md

I was reading the README.md and my eye fell on two typos in the Type hints (`Optioinal` -> `Optional`)

FIX - Typo in type hints in Readme

---

.gitmodules

Using git/ssh protocl for submodule repo prevents us from pulling
connectorx as a cargo dependency by a specific git commit.

pin git submodule using https protocol

---

docs/api.md

Fixed spelling in the api docs.

Correcting Spelling in Docs

---

connectorx-python/connectorx/tests/test_postgres.py
connectorx/src/sources/postgres/typesystem.rs
docs/databases/postgres.md
scripts/postgres.sql

This adds ltree type as a string, using commit as guide 9ae1ecb644742c6aaa29c2f0a0f1e3bd1219bae5. 
ltree is available in the driver since https://github.com/sfackler/rust-postgres/issues/389
Works with all protocols, but has an issue with Binary:
When I inspect the data in the shell, the dataframe that came from Postgres shows this hex prefix.
I'm looking for help delivering this, and other Postgres Types. Thanks!
Fixes: #381

[WIP] Adds ltree string type

---

Types.md
connectorx/src/sources/postgres/typesystem.rs

I just happened to notice these while I was reading through the source (to check for PostgreSQL arrow2 array support - which now exists!) Thanks for the great work :)
PS: any (approximate) date in mind for a 0.3.1 release?

trivial fix: typos

---

connectorx-python/connectorx/tests/test_arrow.py
connectorx/src/transports/postgres_arrow2.rs

Adds Enum to Postgres -> Arrow2
Closes #390

Adds Enum transport in Postgres->Arrow2 +tests

---

connectorx-python/connectorx/__init__.py

Hi! This PR is mostly about compatibility with Polars.
With this, using `return_type="polars"` will have the same result as `polars.from_sql`
Both Polars itself and their integration with this lib uses Arrow2.
Reference to the integration: https://github.com/pola-rs/polars/blob/9dabbe5b4d0d21a65bf6e2a52062175485603a86/py-polars/polars/io.py#L1096
Also, for the from_arrow function, I believe testing the current API and then falling back to the old one should be preferable. But I can remove this from the PR if you disagree.

Polars uses Arrow2 in their code. So should this lib

---

connectorx-python/connectorx/tests/test_arrow.py
connectorx-python/connectorx/tests/test_postgres.py
connectorx/src/sources/postgres/typesystem.rs
connectorx/src/transports/postgres_arrow2.rs
docs/databases/postgres.md
scripts/postgres.sql

Adds: lquery, ltxtquery 
Binary protocol for ltree types will fail in postgres older than 13

Adds support for the rest of the Ltree family + docs on binary protocol

---

Cargo.lock
connectorx/Cargo.toml
connectorx/src/destinations/arrow/arrow_assoc.rs
connectorx/src/sources/sqlite/mod.rs
connectorx/src/transports/postgres_arrow.rs

There are a couple of (related) changes in this PR, all of which underpin the [remote table](https://seafowl.io/docs/guides/remote-tables) functionality that we've recently built on Seafowl: 
- the JSON transport mappings just align the existing implementation in Arrow 2 with the missing one in Arrow.
- likewise, the missing arrow association rules for `DateTime<Utc>` and `Option<DateTime<Utc>>` (PG Timestampz type) are added. Unlike in Arrow 2, we don't have a builder that will collect the Timestamp values with a UTC zone set, so we have to set it to `None` instead.
- finally bump sqlite related libs, and fix resulting conflicts (`columns` and `column_names` function changes).
Basically, we use these changes on our connector-x fork, but given that they are pretty general it may be useful …

Add PG JSON to Arrow transport rules

---

connectorx-python/src/pandas/transports/oracle.rs
connectorx/src/sources/oracle/typesystem.rs
connectorx/src/transports/oracle_arrow.rs
connectorx/src/transports/oracle_arrow2.rs

Changes made to fix the issues mentioned in the issue #469 to make oracle date type conversion display day : hours.
Files changed:
`connectorx-python/src/pandas/transports/oracle.rs`
`connectorx/src/sources/oracle/typesystem.rs`
`connectorx/src/transports/oracle_arrow.rs`
`connectorx/src/transports/oracle_arrow2.rs`

Fixed oracle Date type conversion to fix issue #469

---

connectorx/src/sources/postgres/typesystem.rs
connectorx/src/transports/postgres_arrow2.rs
connectorx/tests/test_polars.rs
scripts/postgres.sql

The goal of this PR is to extend support for the _text type as requested by a user within the issue: https://github.com/sfu-db/connector-x/issues/480. This issue centers around connectorx panicking when interacting with tables containing a text[] type.
To solve this, I added:
- a TextArray type in the various enums in connectorx/src/sources/postgres/typesystem.rs
- a mapping between TextArray and Utf8Array in connectorx/src/transports/postgres_arrow2.rs
- added _text/text[] data to scripts/postgres.sql
- added a test for _text/text[] compatibility with postgres/polars in connectorx/tests/test_polars.rs

Feat/add support for  _text

---

connectorx/src/destinations/arrow/arrow_assoc.rs

It panics when I try to read nullable datetime fields, then I found this incorrect conversion.

fix incorrect nullability for datetime type when writing to arrow

---

connectorx-python/pyproject.toml

I have a py3.7 only project, which is managed by poetry.
But I found that the `connectorx` library does not constrain the python version in the lock file, so It will try to install `connectorx==0.3.2` which has deprecated py3.7 and ultimately fail.

build(pypi): Constrain the python version

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
connectorx-python/Cargo.toml
connectorx/Cargo.toml
connectorx/examples/batch_test.rs
connectorx/src/constants.rs
connectorx/src/sources/bigquery/mod.rs
connectorx/src/sources/mssql/typesystem.rs
connectorx/src/sources/mysql/mod.rs
connectorx/src/sources/oracle/mod.rs
connectorx/src/sources/postgres/mod.rs
connectorx/src/sources/sqlite/mod.rs
connectorx/src/sql.rs
connectorx/tests/test_mssql.rs
connectorx/tests/test_postgres.rs

Also fix the toolchain to stable in workflows.

DataFusion 31 and Arrow 46 upgrade

---

Cargo.lock
connectorx/Cargo.toml

this is the only published crate still depending on v0.5 and is probably the reason for a lot of the downloads of the old version.
note: if you were to enable dependabot updates on connector-x then this wouldn't have to be done manually.

update to `r2d2-oracle=0.6`

---

.gitignore
connectorx/src/sources/postgres/mod.rs
connectorx/tests/test_postgres.rs
scripts/postgres.sql

Fix for a bug with postgres implementation. In postgres many numeric/date data types can have infinite or negative infinite values. Currently when one of these values is selected in connector-x it results in a runtime panic error. This PR fixes this issue for 3 data type (datetime, date, and real).
Resolves Issue 572

 Infinite Postgres Bug #573 

---

.gitignore
Cargo.lock
connectorx/Cargo.toml

Versions of SQLite currently used have some reported vulnerabilities (see output of `cargo audit`). This PR updates the rusqlite version to avoid that. 
I've also added a few .gitignore entries for files I need to build this project.

Update SQLite dependencies

---

connectorx-python/connectorx/connectorx.pyi

Signed-off-by: ZhengYu, Xu <zen-xu@outlook.com>

typing: add stubs for connectorx.so

---

connectorx-python/connectorx/__init__.py

Since python3.7 has been deprecated and `importlib.metadata` is builtin in [python3.8](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata), there is no longer to get version from the backport `importlib_metadata`.

No need to rely on the backport `importlib_metadata` for version retrieval anymore

---

connectorx-python/connectorx/__init__.py

Signed-off-by: ZhengYu, Xu <zen-xu@outlook.com>

refactor: A more Pythonic way to set environment variables.

---

connectorx-python/connectorx/__init__.py

Simplifies `remove_ending_semicolon`.
Origin: https://github.com/sfu-db/connector-x/pull/599#discussion_r1560237717

Re-write `remove_ending_semicolon`

---

connectorx-python/connectorx/__init__.py
connectorx-python/connectorx/tests/test_bigquery.py
connectorx-python/connectorx/tests/test_clickhouse.py
connectorx-python/connectorx/tests/test_mssql.py
connectorx-python/connectorx/tests/test_mysql.py
connectorx-python/connectorx/tests/test_oracle.py
connectorx-python/connectorx/tests/test_redshift.py
connectorx-python/connectorx/tests/test_sqlite.py

This PR can provide some type hints to help build a DB connection.

feat: Supports structured construction of database connection.

---

Cargo.lock
Justfile
README.md
connectorx-cpp/Cargo.toml
connectorx-python/Cargo.lock
connectorx-python/Cargo.toml
connectorx-python/connectorx/tests/test_trino.py
connectorx-python/src/errors.rs
connectorx-python/src/pandas/get_meta.rs
connectorx-python/src/pandas/mod.rs
connectorx-python/src/pandas/transports/mod.rs
connectorx-python/src/pandas/transports/trino.rs
connectorx/Cargo.toml
connectorx/src/lib.rs
connectorx/src/partition.rs
connectorx/src/source_router.rs
connectorx/src/sources/mod.rs
connectorx/src/sources/trino/errors.rs
connectorx/src/sources/trino/mod.rs
connectorx/src/sources/trino/typesystem.rs
connectorx/src/transports/mod.rs
connectorx/src/transports/trino_arrow.rs
connectorx/src/transports/trino_arrow2.rs
connectorx/src/transports/trino_arrowstream.rs
connectorx/tests/test_trino.rs
docs/databases.md
docs/databases/trino.md
scripts/trino.sql

I'd really like to see Trino being implemented as a source in ConnectorX and thus have begun working on it. It uses prusto as a client and currently supports all basic types. Support for tuple, array, row and uuid isn't implemented yet and there's a bug with time columns not being mapped correctly. Also I want to look into fetching results more efficiently and not everything at once.
What do you think, is it worth continuing work on it? Is there anything else I need to consider eg. regarding mapping the results?

implement Trino source

---

connectorx/src/sources/mysql/mod.rs

Encountered with the same problem as #464 and #510 , where `text` type columns in mysql are interpreted as binary ones naively, which is technically ok, according to the [mysql doc](https://dev.mysql.com/doc/refman/8.4/en/blob.html) that the `text` types are basically just `blob` types, except for additional charset requirements. 
But it's quite an inconvenient for users must do decoding themselves on the final result. So I made and tested this patch in our environment as an easy workaround. Note that we only use UTF8 charset for `text` fields in our databases, so this patch only works for UTF8 text fields. For other encodings like GBK, SHIFT_JIS, BIG5, etc., it won't work, additional decoding is still needed.
If anyone interested, I recommend checking out this crate …

read mysql text column (utf8 charset) as string column

---

connectorx-python/connectorx/tests/test_mysql.py
connectorx-python/src/pandas/transports/mysql.rs
connectorx/src/sources/mysql/typesystem.rs
connectorx/src/transports/mysql_arrow.rs
connectorx/src/transports/mysql_arrow2.rs
connectorx/src/transports/mysql_arrowstream.rs
scripts/mysql.sql

Currently, mysql column type `MYSQL_TYPE_BIT` is not supported, panicking the process if present in the table. And this issue is also stated in #359 and #491 .
I think it's appropriate to convert the bit type as longlong i64. According to the [mysql doc](https://dev.mysql.com/doc/refman/8.4/en/bit-type.html) page, bit type columns can store `M`-bit values, with `M` ranging from 1 to 64.

read mysql bit type as i64

---

connectorx/src/sources/oracle/mod.rs
docs/databases/oracle.md

The use of aliases defined in tnsnames.ora is a common connection method found in Oracle, which also enables the specification of communication protocols like TCP/TCPS  (i.e. SSL-enabled) among other configurations through a DSN connection string.
This change adds parameter handling for the connection string defined for an Oracle DB connection. Specifically, the alias boolean parameter when set to true, parses the alias defined in the host directly to the oracle::Connector::new method to initialize the connector object.
For a connection using aliases, the connection string will look as such:
`oracle://<username>:<password>@<alias>?alias=true`
compared to the direct connection string method specifying host & port:
`oracle://<username>:<password>@<host>:<port>/<database>`
This will resolve …

feat: Added Option for Oracle Connector to use Alias w/ Params

---

connectorx-python/pyproject.toml

Benefit: Easier to navigate to the repo/documentation from the pypi page

Add project urls to pyproject.toml

---

.github/workflows/release.yml
README.md

This change re-introduces the Linux ARM Build process to the release workflow and seeks to address the long-standing issue of missing `connector-x` wheels for Linux ARM in #240, #386, #506, #535, #673, #724 and more recently, #773.
With the introduction of GitHub ARM-based runners earlier this year in public preview, it is now possible to build our distribution natively in an ARM-based Ubuntu 22.04 environment, which should allow compatibility with OSes using `glibc 2.35` and above.
A test run can be found in my fork here:
https://github.com/pangjunrong/connector-x/actions/runs/13912310291

feat: Linux ARM Release CICD for `glibc 2.35`

---

README.md
connectorx-python/connectorx/__init__.py
docs/install.md

This change optimizes the reconstruction of Pandas DataFrames using the `_from_sequence` methods for ExtensionArrays, which run on bulk conversion routines using vectorized NumPy operations while avoiding the extra layers of validation in the general constructor.
It also uses the `_from_mgr` method for DataFrame construction using BlockManager, which assumes the BlockManager is already in a valid state and skips the validation and setup overhead that the regular pd.DataFrame(BlockManager) constructor performs.
This also resolves the warnings mentioned in #786.
Based on a simple generic benchmark between the typical class initialization and use of `_from_sequence`, the performance gain seems to be consistent & profound across BooleanArray, DatetimeArray & IntegerArray. However, I will need …

refactor: Optimize DataFrame Reconstruction & Update Docs for Linux ARM64 Release

---

Cargo.lock
Cargo.toml
connectorx-python/Cargo.lock
connectorx-python/Cargo.toml
connectorx/Cargo.toml

Arrow 0.53 (current used by connectorX) does not play well with any crates needing Arrow 0.55 (the latest version of Arrow). For example, datafusion has updated to Arrow 0.55 and is no longer working with Arrow 0.53. For example, a crate that imports the latest version of `connectorx` and of `datafusion` can not compile. See issue here: https://github.com/apache/arrow-rs/issues/7410
```
[dependencies]
connectorx = { version = "0.4", features = ["src_postgres", "dst_arrow"] }
datafusion = "47"
```
Arrow 0.54 seems to play well with 0.55 and 0.53, so that is why I bumped it up to this version only. I fear bumping it up to 0.55 will cause issues with other crate features I can not test (e.g. older version of datafusion).

Bump Arrow to 0.54

---

connectorx-python/connectorx/__init__.py
connectorx-python/connectorx/connectorx.pyi
connectorx-python/connectorx/tests/test_arrow.py
connectorx-python/src/arrow.rs
connectorx-python/src/cx_read_sql.rs
connectorx-python/src/lib.rs
connectorx/src/arrow_batch_iter.rs
connectorx/src/destinations/arrowstream/mod.rs

**Changes**
- Builds on the existing `new_record_batch_iter` to expose a pyarrow `RecordBatchReader` on python side
- Supports completely lazy iterations over arrow stream destination
- Added `kwargs` to `read_sql`, users can pass `record_batch_size` to control the number of records in each record batch.
- fixed a few `unwraps` causing issues
- Updates `RecordBatchReader` trait to support `Send` (helps offload `RecordBatchReader` to multi-threaded consumers like DuckDB)
- Left existing implementations as is, ideally those can also rely on record batch approach
**Usage/ Example**
```py
import connectorx as cx
conn = "mysql://username:password@server:port/database/"
query = "SELECT * FROM employees"
rb_iter = cx.read_sql(
conn,
query,
return_type="arrow_record_batches", …
```

feat(arrow): Allow record batches output from read_sql

---

connectorx-python/src/pandas/transports/postgres.rs
connectorx/src/sources/postgres/mod.rs
connectorx/src/sources/postgres/typesystem.rs
connectorx/src/transports/postgres_arrow.rs

Minor addition of support for the `oid` PostgreSQL identifier type, so it's a little easier to interact with system tables; `oid` is a `u32` type, and can be directly read as such.
Ref: [PostgreSQL OID type details](https://pgpedia.info/o/oid.html#:~:text=unsigned%2032%20bit%20integer).
Loading some data from the `pg_class` system table:
```python
import connectorx as cx
cx.read_sql(
conn="postgresql://<user>:<pass>@<host>:<port>/<db>",
query="""
SELECT oid, relname 
FROM pg_class
WHERE relkind = 't'
""",
return_type="polars",
)
```
**Before:**
```python
```
**After:**
```python
```

feat(postgres): Added support for PostgreSQL `OID` type conversion (as `u32`)
